#!/bin/bash

echo "Teste 1"
./ariis sandbox/novaentrada > sandbox/out-result1
diff sandbox/out-result1 sandbox/out-default1

echo ""

echo "Teste 2"
./ariis sandbox/novaentrada2 > sandbox/out-result2
diff sandbox/out-result2 sandbox/out-default2
